steps:
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: sh
   args:
     - '-c'
     - "docker build -f src/emailservice/Dockerfile --tag=gcr.io/$PROJECT_ID/emailservice:v0.1.1-4-g$SHORT_SHA --build-arg BLDDATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') --build-arg REPO_NAME=$REPO_NAME --build-arg COMMIT_SHA=$COMMIT_SHA --build-arg GIT_TAG=$(git describe --tags --exact-match || git symbolic-ref -q --short HEAD) src/emailservice"

images: 
  - 'gcr.io/$PROJECT_ID/emailservice:v0.1.1-4-g$SHORT_SHA'
  
